package com.piconector.bks;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2020-12-29T17:44:48.261-05:00
 * Generated source version: 3.4.1
 *
 */
@WebService(targetNamespace = "http://bks.piconector.com", name = "PIConectorBKS")
@XmlSeeAlso({com.piconector.beans.ObjectFactory.class, ObjectFactory.class, com.piconector.config.ObjectFactory.class, com.imdea.gestorimagenes.beans.ObjectFactory.class, com.piconector.tracking.ObjectFactory.class})
public interface PIConectorBKS {

    @WebMethod(action = "generarDocumentoDatosEnColaBatch")
    @RequestWrapper(localName = "generarDocumentoDatosEnColaBatch", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GenerarDocumentoDatosEnColaBatch")
    @ResponseWrapper(localName = "generarDocumentoDatosEnColaBatchResponse", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GenerarDocumentoDatosEnColaBatchResponse")
    @WebResult(name = "generarDocumentoDatosEnColaBatchReturn", targetNamespace = "")
    public java.lang.String generarDocumentoDatosEnColaBatch(

        @WebParam(name = "idDocumentoMQ", targetNamespace = "")
        java.lang.String idDocumentoMQ
    );

    @WebMethod(action = "generarPurgadoRepositorioTemporal")
    @RequestWrapper(localName = "generarPurgadoRepositorioTemporal", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GenerarPurgadoRepositorioTemporal")
    @ResponseWrapper(localName = "generarPurgadoRepositorioTemporalResponse", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GenerarPurgadoRepositorioTemporalResponse")
    public void generarPurgadoRepositorioTemporal()
;

    @WebMethod(action = "generaComposicion")
    @RequestWrapper(localName = "generaComposicion", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GeneraComposicion")
    @ResponseWrapper(localName = "generaComposicionResponse", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GeneraComposicionResponse")
    @WebResult(name = "generaComposicionReturn", targetNamespace = "")
    public java.lang.String generaComposicion(

        @WebParam(name = "datos", targetNamespace = "")
        java.lang.String datos
    );

    @WebMethod(action = "generaDocumentoHTMLAutocontenido")
    @RequestWrapper(localName = "generaDocumentoHTMLAutocontenido", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GeneraDocumentoHTMLAutocontenido")
    @ResponseWrapper(localName = "generaDocumentoHTMLAutocontenidoResponse", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GeneraDocumentoHTMLAutocontenidoResponse")
    @WebResult(name = "generaDocumentoHTMLAutocontenidoReturn", targetNamespace = "")
    public java.lang.String generaDocumentoHTMLAutocontenido(

        @WebParam(name = "datos", targetNamespace = "")
        java.lang.String datos
    );

    @WebMethod(action = "generaDocumentoDatosEnColaURL")
    @RequestWrapper(localName = "generaDocumentoDatosEnColaURL", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GeneraDocumentoDatosEnColaURL")
    @ResponseWrapper(localName = "generaDocumentoDatosEnColaURLResponse", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GeneraDocumentoDatosEnColaURLResponse")
    @WebResult(name = "generaDocumentoDatosEnColaURLReturn", targetNamespace = "")
    public java.lang.String generaDocumentoDatosEnColaURL(

        @WebParam(name = "idDocumentoMQ", targetNamespace = "")
        java.lang.String idDocumentoMQ
    );

    @WebMethod(action = "generaDocumentoDatosEnCola")
    @RequestWrapper(localName = "generaDocumentoDatosEnCola", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GeneraDocumentoDatosEnCola")
    @ResponseWrapper(localName = "generaDocumentoDatosEnColaResponse", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GeneraDocumentoDatosEnColaResponse")
    @WebResult(name = "generaDocumentoDatosEnColaReturn", targetNamespace = "")
    public java.lang.String generaDocumentoDatosEnCola(

        @WebParam(name = "idDocumentoMQ", targetNamespace = "")
        java.lang.String idDocumentoMQ
    );

    @WebMethod(action = "obtenerFicheroConfiguracion")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "obtenerFicheroConfiguracionResponse", targetNamespace = "http://config.piconector.com", partName = "parameters")
    public com.piconector.config.ObtenerFicheroConfiguracionResponse obtenerFicheroConfiguracion(

        @WebParam(partName = "parameters", name = "obtenerFicheroConfiguracion", targetNamespace = "http://bks.piconector.com")
        ObtenerFicheroConfiguracion parameters
    );

    @WebMethod(action = "setPic")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "setPicResponse", targetNamespace = "http://bks.piconector.com", partName = "parameters")
    public SetPicResponse setPic(

        @WebParam(partName = "parameters", name = "setPic", targetNamespace = "http://bks.piconector.com")
        SetPic parameters
    );

    @WebMethod(action = "reenviarDocumento")
    @RequestWrapper(localName = "reenviarDocumento", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.ReenviarDocumento")
    @ResponseWrapper(localName = "reenviarDocumentoResponse", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.ReenviarDocumentoResponse")
    @WebResult(name = "reenviarDocumentoReturn", targetNamespace = "")
    public java.lang.String reenviarDocumento(

        @WebParam(name = "datos", targetNamespace = "")
        java.lang.String datos
    );

    @WebMethod(action = "removePic")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "removePicResponse", targetNamespace = "http://bks.piconector.com", partName = "parameters")
    public RemovePicResponse removePic(

        @WebParam(partName = "parameters", name = "removePic", targetNamespace = "http://bks.piconector.com")
        RemovePic parameters
    );

    @WebMethod(action = "generaDocumento")
    @RequestWrapper(localName = "generaDocumento", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GeneraDocumento")
    @ResponseWrapper(localName = "generaDocumentoResponse", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GeneraDocumentoResponse")
    @WebResult(name = "generaDocumentoReturn", targetNamespace = "")
    public java.lang.String generaDocumento(

        @WebParam(name = "datos", targetNamespace = "")
        java.lang.String datos
    );

    @WebMethod(action = "obtenerEstadoBatch")
    @RequestWrapper(localName = "obtenerEstadoBatch", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.ObtenerEstadoBatch")
    @ResponseWrapper(localName = "obtenerEstadoBatchResponse", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.ObtenerEstadoBatchResponse")
    @WebResult(name = "obtenerEstadoBatchReturn", targetNamespace = "")
    public java.lang.String obtenerEstadoBatch(

        @WebParam(name = "datos", targetNamespace = "")
        java.lang.String datos
    );

    @WebMethod(action = "obtenerEstadoReenvio")
    @RequestWrapper(localName = "obtenerEstadoReenvio", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.ObtenerEstadoReenvio")
    @ResponseWrapper(localName = "obtenerEstadoReenvioResponse", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.ObtenerEstadoReenvioResponse")
    @WebResult(name = "obtenerEstadoReenvioReturn", targetNamespace = "")
    public java.lang.String obtenerEstadoReenvio(

        @WebParam(name = "datos", targetNamespace = "")
        java.lang.String datos
    );

    @WebMethod(action = "devuelveXmlTracking")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "devuelveXmlTrackingResponse", targetNamespace = "http://tracking.piconector.com", partName = "parameters")
    public com.piconector.tracking.DevuelveXmlTrackingResponse devuelveXmlTracking(

        @WebParam(partName = "parameters", name = "devuelveXmlTracking", targetNamespace = "http://bks.piconector.com")
        DevuelveXmlTracking parameters
    );

    @WebMethod(action = "getAllPic")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getAllPicResponse", targetNamespace = "http://bks.piconector.com", partName = "parameters")
    public GetAllPicResponse getAllPic(

        @WebParam(partName = "parameters", name = "getAllPic", targetNamespace = "http://bks.piconector.com")
        GetAllPic parameters
    );

    @WebMethod(action = "addPic")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "addPicResponse", targetNamespace = "http://bks.piconector.com", partName = "parameters")
    public AddPicResponse addPic(

        @WebParam(partName = "parameters", name = "addPic", targetNamespace = "http://bks.piconector.com")
        AddPic parameters
    );

    @WebMethod(action = "getPic")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getPicResponse", targetNamespace = "http://bks.piconector.com", partName = "parameters")
    public GetPicResponse getPic(

        @WebParam(partName = "parameters", name = "getPic", targetNamespace = "http://bks.piconector.com")
        GetPic parameters
    );

    @WebMethod(action = "generaDocumentoURL")
    @RequestWrapper(localName = "generaDocumentoURL", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GeneraDocumentoURL")
    @ResponseWrapper(localName = "generaDocumentoURLResponse", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GeneraDocumentoURLResponse")
    @WebResult(name = "generaDocumentoURLReturn", targetNamespace = "")
    public java.lang.String generaDocumentoURL(

        @WebParam(name = "datos", targetNamespace = "")
        java.lang.String datos
    );

    @WebMethod(action = "generarDocumentoBatch")
    @RequestWrapper(localName = "generarDocumentoBatch", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GenerarDocumentoBatch")
    @ResponseWrapper(localName = "generarDocumentoBatchResponse", targetNamespace = "http://bks.piconector.com", className = "com.piconector.bks.GenerarDocumentoBatchResponse")
    @WebResult(name = "generarDocumentoBatchReturn", targetNamespace = "")
    public java.lang.String generarDocumentoBatch(

        @WebParam(name = "datos", targetNamespace = "")
        java.lang.String datos
    );
}
