package com.piconector.bks;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2020-12-29T17:44:48.411-05:00
 * Generated source version: 3.4.1
 *
 */
@WebServiceClient(name = "PIConectorBKSService",
                  wsdlLocation = "file:/D:/2-WorkSpaces/Wk%20Camel/SoapExample/src/main/resources/wsdl/prueba5.wsdl",
                  targetNamespace = "http://bks.piconector.com")
public class PIConectorBKSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bks.piconector.com", "PIConectorBKSService");
    public final static QName PIConectorBKS = new QName("http://bks.piconector.com", "PIConectorBKS");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/2-WorkSpaces/Wk%20Camel/SoapExample/src/main/resources/wsdl/prueba5.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PIConectorBKSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/2-WorkSpaces/Wk%20Camel/SoapExample/src/main/resources/wsdl/prueba5.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PIConectorBKSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PIConectorBKSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PIConectorBKSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PIConectorBKSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PIConectorBKSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PIConectorBKSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PIConectorBKS
     */
    @WebEndpoint(name = "PIConectorBKS")
    public PIConectorBKS getPIConectorBKS() {
        return super.getPort(PIConectorBKS, PIConectorBKS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PIConectorBKS
     */
    @WebEndpoint(name = "PIConectorBKS")
    public PIConectorBKS getPIConectorBKS(WebServiceFeature... features) {
        return super.getPort(PIConectorBKS, PIConectorBKS.class, features);
    }

}
